### ISSUE TITLE
Time issue after oppenent refuses score

### ISSUE THREAD

**Issue by sorianom** [openfoxwq/openfoxwq_client#10]
Hi,

In my game using this client the opponent asked to score and then declined the result. After that, the system was showing as if the opponent was using his time. However, when the time eventually ran out, the server declared that I had lost the game on time. Hence, it seems like the client is not showing the time correctly after there is an attempt to score the game.

The game ran using the 20min + 3x1min pre-set on 19x19. Curiously, the number of byoyomi times left was showing on my side, while the actual time running out was showing on the opponent side. Hence, when the game was over, the opponent time was showing as 3 x 0, while my time was showing as 1 x 1min.

**Comment by ale64bit** [comment]
This is likely due to either openfoxwq not handling user disconnections or the connection between the proxy and the web client being broken. Either way, note that I won't be developing openfoxwq further. Instead, you might want to take a look at minifox here https://openfoxwq.github.io/ and/or join our Discord server to know more.
