### ISSUE TITLE
Any plans for supporting the score estimator?

### ISSUE THREAD

**Issue by acosmicjoke** [openfoxwq/openfoxwq_client#11]
The official client has a quite accurate in-game score estimator. I feel it's quite a handicap to play without it when your opponent has access. Any plans on implementing it in this client? I have no idea if the estimation is done client or server side in the official client though.

**Comment by ale64bit** [comment]
In principle, I would like to support it. It's challenging because it's entirely client-side and requires quite a bit of effort. I did investigate a bit and collected some info (see [here](https://discord.com/channels/1077299199684653126/1141811379158921266/1159057981921574962)), but I haven't been able to complete it. Any help in this direction would be appreciated.
