### ISSUE TITLE
Where do we go for support with the new minifox app?

### ISSUE THREAD

**Issue by adamreisnz** [openfoxwq/openfoxwq_client#13]
I appreciate this project is being discontinued, and there is now going to be a minifox app, but that one is not open source and therefore I don't think there is a repository/place to report bugs or issues.

The popup in the openfox client says that people using openfox should be happy to use minifox, but after I launch minifox this is all I see, and quite frankly, it doesn't really make me very happy, as the interface looks broken and it's all very blurry:

<img width="1483" alt="image" src="https://github.com/openfoxwq/openfoxwq_client/assets/490562/d9b871cc-38ee-406d-9bc8-f17d782efeb9">

Is this just an early alpha version?
Can we keep the openfox client running for a bit longer please until the minifox client is sorted out?

I am happy to take over the project if need be.

**Comment by ale64bit** [comment]
> I appreciate this project is being discontinued, and there is now going to be a minifox app, but that one is not open source and therefore I don't think there is a repository/place to report bugs or issues.
> 

Most interaction happens in our Discord server: https://discord.gg/RG2KquNWKE. Feel free to join us.

> The popup in the openfox client says that people using openfox should be happy to use minifox, but after I launch minifox this is all I see, and quite frankly, it doesn't really make me very happy, as the interface looks broken and it's all very blurry:

This is what it shows the first time, and you are supposed to arrange the windows according to your preference. It's fairly flexible. Once they are arranged in any specific way, this configuration is remembered by the application and you don't need to do it again. I say *should be happy*, precisely because maybe it's not to everyone's liking. From the current feedback, it would seem that many do prefer minifox. Could you also clarify what exactly is blurry and which OS is this?

> 
> Is this just an early alpha version? Can we keep the openfox client running for a bit longer please until the minifox client is sorted out?


All versions are alpha :) this is a volunteer project that depends on a reverse-engineered API. The web client will be discontinued at the end of the year. Feel free to join our Discord server and we can discuss which issues exactly remain with minifox which need to be sorted out.

> 
> I am happy to take over the project if need be.

We can also discuss this is you're interested. But be aware that I won't be maintaining the proxy as well, which might make it challenging for you when the protocol changes/updates/breaks.

**Comment by adamreisnz** [comment]
Hi @ale64bit, thanks for the response.

The blurriness affects everything, the whole app. I don't think it factors in retina displays. Normally for retina displays when graphical non-vectorised operations are involved (e.g cavnas) the whole graphics are scaled 2x to adjust for retina displays and to make things look sharp.

I will attach a screenshot, but if this is not viewed on a retina display, or if you don't have one, you may not see the difference.

<img width="628" alt="image" src="https://github.com/openfoxwq/openfoxwq_client/assets/490562/f108e66d-9e5c-48fd-bdd9-9708b1ac80a9">

There's quite a few other interface related bugs, like when resizing the window everything is being stretched, but I assume you are aware of those. Also, I tried a first game today, but I was disconnected from the server after about 20 moves.

The web client just seemed to work much better and was more reliable from what I have experienced. It's a shame it will be discontinued.

**Comment by ale64bit** [comment]
> Hi @ale64bit, thanks for the response.
> 
> The blurriness affects everything, the whole app. I don't think it factors in retina displays. Normally for retina displays when graphical non-vectorised operations are involved (e.g cavnas) the whole graphics are scaled 2x to adjust for retina displays and to make things look sharp.
> 

I'm not using a Retina display, so it's possible. I'm using [imgui](https://github.com/ocornut/imgui) for the GUI and it might need some tweaks for those. I'll look into it. Thanks for reporting.

> There's quite a few other interface related bugs, like when resizing the window everything is being stretched, but I assume you are aware of those. 

This is WAI. As I mentioned, I'm using imgui which doesn't use the platform-specific widgets or windows (like e.g. Qt). Instead it has its own system rendered inside the host window. I would appreciate if you describe the other interface-related bugs so that I can take a look at them.

> Also, I tried a first game today, but I was disconnected from the server after about 20 moves.
> 

That's unfortunate. However, any disconnection you get in minifoxwq, you will also get in openfoxwq since they are built the same way. Moreover, you will get additional disconnections in openfoxwq web client due to the extra proxy hop and reconnection attempts with the proxy.

Also, I believe that yesterday there were quite a few issues with fox servers. Several people reported disconnection problems in our Discord. You can always log back in and it should reopen the game you were playing.

> The web client just seemed to work much better and was more reliable from what I have experienced. It's a shame it will be discontinued.

I'm sorry about that. You can read more about the reasons in the Discord announcement.

**Comment by adamreisnz** [comment]
>  I'm not using a Retina display, so it's possible. I'm using [imgui](https://github.com/ocornut/imgui) for the GUI and it might need some tweaks for those. I'll look into it. Thanks for reporting.

Thanks, that'd be great.

>  I would appreciate if you describe the other interface-related bugs so that I can take a look at them.

Well, it was mainly the initial state of the windows, which was really tiny and as a new user you don't really understand what is going on and it's not intuitive that you have to manually resize the windows. I think the app should probably have a more intuitive and reasonable initial state, where the windows take up whatever space is available etc. But there may be technical limitations given the software/framework you're using.

Second problem was as described above, but you said it's working as intended. E.g. when the window is resized, the content stretches or shrinks, rather than staying in place in the same size, which is quite unnatural behaviour. I've never seen that in any app as it makes the text unreadable when shrunk/expanded. But again, could be side effect of the UI framework.

> That's unfortunate. However, any disconnection you get in minifoxwq, you will also get in openfoxwq since they are built the same way. Moreover, you will get additional disconnections in openfoxwq web client due to the extra proxy hop and reconnection attempts with the proxy.

This has not been my experience. I played on openfoxwq right after the disconnect happened, and was able to play a full game without any issues. I've also not experienced any server disconnect when using openfoxwq at all during any previous games that I played there.

When I tried minifoxwq, the disconnect happened very quickly into the game and when I logged back in, it did take me back to the game but then the opponent quit as they probably thought I was mucking around.

Could have been a one-off with especially bad timing, but to me it came across as the app just being less stable. Could have been bad luck though, so I will try again and see if it is a recurring issue.

I was not using a proxy.

**Comment by ale64bit** [comment]
> Well, it was mainly the initial state of the windows, which was really tiny and as a new user you don't really understand what is going on and it's not intuitive that you have to manually resize the windows. I think the app should probably have a more intuitive and reasonable initial state, where the windows take up whatever space is available etc. But there may be technical limitations given the software/framework you're using.
> 

I agree with you that it would be better if the initial state was something more sane. IIRC this was brought up by another confused user once when they opened it for the first time. I'll look into it.

> Second problem was as described above, but you said it's working as intended. E.g. when the window is resized, the content stretches or shrinks, rather than staying in place in the same size, which is quite unnatural behaviour. I've never seen that in any app as it makes the text unreadable when shrunk/expanded. But again, could be side effect of the UI framework.
> 

I'm not sure I fully understand this one. If I resize the window, while the resize drag is held, it does show the content stretching/shrinking. However, when the resize drag is released, the content remains the same size it was before (possibly clipped) regardless of the new window size. This is what I meant that was working as intended. Is this not what you observe?
 
> This has not been my experience. I played on openfoxwq right after the disconnect happened, and was able to play a full game without any issues. I've also not experienced any server disconnect when using openfoxwq at all during any previous games that I played there.
> 
> When I tried minifoxwq, the disconnect happened very quickly into the game and when I logged back in, it did take me back to the game but then the opponent quit as they probably thought I was mucking around.
> 
> Could have been a one-off with especially bad timing, but to me it came across as the app just being less stable. Could have been bad luck though, so I will try again and see if it is a recurring issue.
> 

Like I said, yesterday there seemed to be quite a few issues with foxwq servers, as reported by other users and I experienced myself. But if it happens recurrently, I would love to know more to understand the issue better. It's not uncommon at least for me to keep minifox open for days without any disconnect at all.

> I was not using a proxy.

I meant the openfoxwq proxy. To be more precise, the openfoxwq web client doesn't connect directly to the foxwq servers. It connects via websocket to a proxy which I host in Google Cloud which in turns connects to the foxwq servers. This proxy application is very similar to minifox. However, the extra hop means that you will get additional disconnections compared to using minifox.
