### ISSUE TITLE
Bug? Opponent timed out, but the game froze at 00:00

### ISSUE THREAD

**Issue by jsepia** [openfoxwq/openfoxwq_client#4]
**Steps:**

1. Begin playing a game. Main time: 20 min; Byo-yomi: 3x 1 min.
2. Opponent quits and leaves the game open as their time is counting down
3. Main time runs out, opponent goes into the first byo-yomi. The opponent's timer shows "3x 0:59", "3x 0:58"...
4. The first byo-yomi ends. The opponent's timer shows "3x 0:00" and stays there.
5. Even after all remaining byo-yomis should be done, the UI remains frozen at 3x 0:00. Nothing changes. The game does not appear to end.
6. The official Fox client shows that the game ended with "B+ Forf" so I guess the game did end on Fox's end. (EDIT: If I understand this correctly, it shows I lost. Maybe I got disconnected?)

**Expected result:**

1. After the first byo-yomi, the second byo-yomi should begin and the timer should display "2x 1:00" or "2x 0:59"
2. After an opponent runs out of main time and byo-yomis, the game should end.

**Screenshots:**

![image](https://github.com/openfoxwq/openfoxwq_client/assets/102862/884b822b-61b6-42ba-b6d0-35b8c4e968f6)

![Untitled4](https://github.com/openfoxwq/openfoxwq_client/assets/102862/f51e53b5-bcdc-48e6-9ae8-a165df960a8b)

**Additional notes:**

Before playing this game, I had trouble logging in. It kept saying the client got disconnected from the server. Could this be related to why it got stuck on byo-yomi?

**Comment by ale64bit** [comment]
Hi and thanks for reporting.

This issue has been brought up several times in the Discord by other users. Unfortunately, I'm not sure what the problem is. I suspect it's related to some message getting lost when the client reconnects to the proxy during a game. It happens rarely but unfortunately it's very annoying. Some people simply refresh the page when they notice that something is going on (while you are not logged in, even if you were in a game, your timer doesn't tick because fox server considers that you are disconnected for a while). While using the native app, this has never happened to me personally, presumably because the proxy is bundled with the client and there's no message loss in that case.

(it's of course possible that fox server itself was down. This happens occasionally. However, the bug still remains)

**Comment by ale64bit** [comment]
Please see https://openfoxwq.github.io/. This issue should not exist in minifox, which also can handle user disconnections.
