### ISSUE TITLE
There is no way to find out that the user is playing no-komi game.

### ISSUE THREAD

**Issue by lukaszlew** [openfoxwq/openfoxwq_client#8]
Sometimes when playing auto-match games, they turn out to be no-komi games (at least based on the sgf).
There is no way to know the komi during the game, which of course affects how one would play.
Can we display a warning on games with unusal komi?

**Comment by ale64bit** [comment]
In no-komi games, the komi is displayed as `0.5` instead of the usual `7.5` since auto-match uses Chinese rules (see screenshot below). Does it show differently for you?

![Screenshot 2023-10-01 at 11 25 07](https://github.com/openfoxwq/openfoxwq_client/assets/9343380/6b1758e9-5ddd-444d-bcfb-7b1312a3543a)
